/**
 * Tests for Sass utility functions.
 */

import { describe, it, expect } from 'vitest';
import {
  toVariableName,
  generateHeader,
  quoteFontFamily,
  generateUseStatement,
  generatePaletteCode,
} from '../../utils/sass.js';

describe('toVariableName', () => {
  it('converts spaces to hyphens', () => {
    expect(toVariableName('My Theme')).toBe('my-theme');
  });

  it('converts to lowercase', () => {
    expect(toVariableName('DARK_THEME')).toBe('dark-theme');
  });

  it('handles mixed case with numbers', () => {
    expect(toVariableName('Theme_v2_Test')).toBe('theme-v2-test');
  });

  it('removes invalid characters', () => {
    expect(toVariableName('Theme@#$%')).toBe('theme');
  });

  it('collapses multiple hyphens', () => {
    expect(toVariableName('my---theme')).toBe('my-theme');
  });

  it('removes leading and trailing hyphens', () => {
    expect(toVariableName('-my-theme-')).toBe('my-theme');
  });

  it('throws on empty input', () => {
    expect(() => toVariableName('')).toThrow('Variable name cannot be empty');
  });

  it('throws on whitespace-only input', () => {
    expect(() => toVariableName('   ')).toThrow('Variable name cannot be empty');
  });

  it('throws when result would be empty', () => {
    expect(() => toVariableName('@#$%')).toThrow('Cannot create valid Sass variable name');
  });
});

describe('generateHeader', () => {
  it('generates a comment header with description', () => {
    const result = generateHeader('Custom palette');
    expect(result).toContain('Generated by Ignite UI Theming MCP Server');
    expect(result).toContain('Custom palette');
  });

  it('produces valid Sass comments', () => {
    const result = generateHeader('Test');
    const lines = result.split('\n');
    expect(lines.every((line) => line.startsWith('//'))).toBe(true);
  });
});

describe('quoteFontFamily', () => {
  it('quotes unquoted single font names', () => {
    expect(quoteFontFamily('Roboto')).toBe("'Roboto'");
  });

  it('leaves already single-quoted fonts unchanged', () => {
    expect(quoteFontFamily("'Roboto'")).toBe("'Roboto'");
  });

  it('leaves already double-quoted fonts unchanged', () => {
    expect(quoteFontFamily('"Roboto"')).toBe('"Roboto"');
  });

  it('wraps font stacks with double quotes when they contain single quotes', () => {
    const input = "'Titillium Web', sans-serif";
    expect(quoteFontFamily(input)).toBe(`"'Titillium Web', sans-serif"`);
  });

  it('wraps font stacks with single quotes when they contain double quotes', () => {
    const input = '"Titillium Web", sans-serif';
    expect(quoteFontFamily(input)).toBe(`'"Titillium Web", sans-serif'`);
  });
});

describe('generateUseStatement', () => {
  it('generates Angular import for angular platform', () => {
    const result = generateUseStatement('angular');
    expect(result).toBe('@use "igniteui-angular/theming" as *;');
  });

  it('generates generic import for webcomponents platform', () => {
    const result = generateUseStatement('webcomponents');
    expect(result).toBe("@use 'igniteui-theming' as *;");
  });

  it('generates generic import when platform is undefined', () => {
    const result = generateUseStatement();
    expect(result).toBe("@use 'igniteui-theming' as *;");
  });
});

describe('generatePaletteCode', () => {
  it('generates palette code with required parameters', () => {
    const result = generatePaletteCode({
      primary: '#2ab759',
      secondary: '#f7bd32',
      surface: 'white',
    });

    expect(result.variableName).toBe('$custom-light-palette');
    expect(result.paletteDefinition.join('\n')).toContain('$primary: #2ab759');
    expect(result.paletteDefinition.join('\n')).toContain('$secondary: #f7bd32');
    expect(result.paletteDefinition.join('\n')).toContain('$surface: white');
  });

  it('uses custom variable name when provided', () => {
    const result = generatePaletteCode({
      primary: '#2ab759',
      secondary: '#f7bd32',
      surface: 'white',
      variableName: 'my-brand',
    });

    expect(result.variableName).toBe('$my-brand');
  });

  it('uses dark variant in variable name', () => {
    const result = generatePaletteCode({
      primary: '#2ab759',
      secondary: '#f7bd32',
      surface: '#121212',
      variant: 'dark',
    });

    expect(result.variableName).toBe('$custom-dark-palette');
  });

  it('includes optional colors when provided', () => {
    const result = generatePaletteCode({
      primary: '#2ab759',
      secondary: '#f7bd32',
      surface: 'white',
      gray: '#333',
      info: '#0288d1',
      success: '#4caf50',
      warn: '#ff9800',
      error: '#f44336',
    });

    const code = result.paletteDefinition.join('\n');
    expect(code).toContain('$gray: #333');
    expect(code).toContain('$info: #0288d1');
    expect(code).toContain('$success: #4caf50');
    expect(code).toContain('$warn: #ff9800');
    expect(code).toContain('$error: #f44336');
  });

  it('generates variable references when useVariableReferences is true', () => {
    const result = generatePaletteCode({
      primary: '#2ab759',
      secondary: '#f7bd32',
      surface: 'white',
      useVariableReferences: true,
    });

    expect(result.colorVariables).toContain('$primary-color: #2ab759;');
    expect(result.colorVariables).toContain('$secondary-color: #f7bd32;');
    expect(result.colorVariables).toContain('$surface-color: white;');
    expect(result.paletteDefinition.join('\n')).toContain('$primary: $primary-color');
  });
});
