/**
 * Ignite UI for Web Components Platform Knowledge
 *
 * This module contains platform-specific information for generating
 * valid Sass theme code for Ignite UI for Web Components applications.
 *
 * Key differences from Angular:
 * - Uses `igniteui-theming` directly (not forwarded through another module)
 * - No `core()` or `theme()` mixins - uses individual mixins: `palette()`, `typography()`, `elevations()`
 * - Ships precompiled CSS themes, but users can install igniteui-theming for custom Sass themes
 * - Components use ThemingController for runtime theme switching via CSS variables
 * - Generated CSS variables follow --ig-* naming convention
 */

import {
  quoteFontFamily,
  generateUseStatement,
  generatePaletteCode,
  generateTypographyCode,
  generateElevationsCode,
} from '../../utils/sass.js';
import { DesignSystem, ThemeVariant } from '../../utils/types.js';
import {PALETTE_PRESETS, type PalettePresetName} from '../palettes.js';
import { ELEVATIONS, PALETTE_PRESETS_PATHS, TYPOGRAPHY_PRESETS_PATHS } from './common.js';

export const WEBCOMPONENTS_PLATFORM = {
  id: 'webcomponents',
  name: 'Ignite UI for Web Components',
  packageName: 'igniteui-webcomponents',

  /**
   * The Sass module to import for theming
   */
  themingModule: 'igniteui-theming',

  /**
   * Detection patterns in package.json dependencies
   */
  detectionPatterns: ['igniteui-webcomponents', '@infragistics/igniteui-webcomponents'],

  /**
   * No required root class (themes apply via CSS variables on :root)
   */
  rootClass: null,
} as const;

/**
 * Template for generating a complete Web Components theme
 */
export interface WebComponentsThemeTemplate {
  designSystem: DesignSystem;
  variant: ThemeVariant;
  primaryColor?: string;
  secondaryColor?: string;
  surfaceColor?: string;
  grayColor?: string;
  customPaletteName?: string;
  /** Custom font family (e.g., "'Inter', sans-serif") */
  fontFamily?: string;
  includeTypography?: boolean;
  includeElevations?: boolean;
  includeSpacing?: boolean;
}

// ============================================================================
// HELPER FUNCTIONS FOR CODE GENERATION
// These smaller functions make the code more testable and maintainable
// ============================================================================

/**
 * Generate the file header comment for Web Components themes.
 */
export function generateWCHeader(): string[] {
  return ['// Generated by Ignite UI Theming MCP Server', '// Platform: Ignite UI for Web Components', ''];
}

/**
 * Get the elevation preset variable for a design system.
 */
export function getWCElevationPreset(designSystem: DesignSystem): string {
  return ELEVATIONS[designSystem];
}

/**
 * Generate import statements for a Web Components theme.
 */
export function generateWCImports(options: {
  designSystem: DesignSystem;
  variant: ThemeVariant;
  hasCustomColors: boolean;
  includeTypography: boolean;
  includeElevations: boolean;
}): string[] {
  const {designSystem, variant, hasCustomColors, includeTypography, includeElevations} = options;
  const lines: string[] = [];

  if (hasCustomColors) {
    // Custom palette: import main module first
    lines.push('// Import the theming module');
    lines.push(generateUseStatement('webcomponents'));

    if (includeTypography) {
      const typographyModule = TYPOGRAPHY_PRESETS_PATHS[designSystem];
      lines.push(`@use '${typographyModule}' as *;`);
    }

    if (includeElevations) {
      lines.push("@use 'igniteui-theming/sass/elevations/presets' as *;");
    }
  } else {
    // Preset palette: import palette first, then theming module
    const paletteModule = PALETTE_PRESETS_PATHS[variant][designSystem];
    lines.push('// Import palette preset');
    lines.push(`@use '${paletteModule}' as *;`);
    lines.push('');
    lines.push('// Import base theme configuration');
    lines.push(generateUseStatement('webcomponents'));

    if (includeTypography) {
      const typographyModule = TYPOGRAPHY_PRESETS_PATHS[designSystem];
      lines.push(`@use '${typographyModule}' as *;`);
    }

    if (includeElevations) {
      lines.push("@use 'igniteui-theming/sass/elevations/presets' as *;");
    }
  }

  return lines;
}

/**
 * Generate CSS @property declarations for progress tracking.
 * These are required by some components.
 */
export function generateWCProgressProperties(indent = ''): string[] {
  return [
    `${indent}@property --_progress-integer {`,
    `${indent}  syntax: '<integer>';`,
    `${indent}  initial-value: 0;`,
    `${indent}  inherits: true;`,
    `${indent}}`,
    '',
    `${indent}@property --_progress-fraction {`,
    `${indent}  syntax: '<integer>';`,
    `${indent}  initial-value: 0;`,
    `${indent}  inherits: true;`,
    `${indent}}`,
  ];
}

/**
 * Generate :root CSS variables for theme configuration.
 */
export function generateWCRootVariables(options: {
  designSystem: DesignSystem;
  variant: ThemeVariant;
  usePaletteMap?: boolean;
  indent?: string;
}): string[] {
  const {designSystem, variant, usePaletteMap = false, indent = ''} = options;
  const lines: string[] = [];

  lines.push(`${indent}:root {`);

  if (usePaletteMap) {
    // When using a palette variable, get theme from the palette's metadata
    lines.push(`${indent}  --ig-theme: #{map.get($palette, '_meta', 'variant')};`);
    lines.push(`${indent}  --ig-theme-variant: #{$variant};`);
  } else {
    // When using preset palette, use literal values
    lines.push(`${indent}  --ig-theme: ${designSystem};`);
    lines.push(`${indent}  --ig-theme-variant: ${variant};`);
  }

  lines.push(`${indent}  --ig-size-small: 1;`);
  lines.push(`${indent}  --ig-size-medium: 2;`);
  lines.push(`${indent}  --ig-size-large: 3;`);
  lines.push(`${indent}  --ig-scrollbar-size: #{rem(16px)};`);
  lines.push(`${indent}}`);

  return lines;
}

/**
 * Generate RTL direction support.
 */
export function generateWCRtlSupport(indent = ''): string[] {
  return [`${indent}body[dir='rtl'] {`, `${indent}  --ig-dir: -1;`, `${indent}}`];
}

/**
 * Generate scrollbar customization using palette colors.
 */
export function generateWCScrollbarCustomization(): string[] {
  return [
    '// Scrollbar customization',
    ':root {',
    '  --ig-scrollbar-thumb-background: #{color($color: gray, $variant: 400)};',
    '  --ig-scrollbar-track-background: #{color($color: gray, $variant: 100)};',
    '}',
  ];
}

/**
 * Generate theming mixin calls (palette, elevations, typography, spacing).
 */
export function generateWCThemingMixins(options: {
  paletteVar: string;
  typefaceValue: string;
  elevationsVar: string;
  includeTypography: boolean;
  includeElevations: boolean;
  includeSpacing: boolean;
  indent?: string;
  addComments?: boolean;
}): string[] {
  const {
    paletteVar,
    typefaceValue,
    elevationsVar,
    includeTypography,
    includeElevations,
    includeSpacing,
    indent = '',
    addComments = false,
  } = options;

  const lines: string[] = [];

  // Palette mixin
  if (addComments) lines.push(`${indent}// Apply palette CSS variables`);
  lines.push(`${indent}@include palette(${paletteVar});`);
  if (addComments) lines.push('');

  // Elevations mixin
  if (includeElevations) {
    if (addComments) lines.push(`${indent}// Apply elevation CSS variables`);
    lines.push(...generateElevationsCode({elevationsVar, indent}));
    if (addComments) lines.push('');
  }

  // Typography mixin
  if (includeTypography) {
    if (addComments) lines.push(`${indent}// Apply typography CSS variables`);
    lines.push(
      ...generateTypographyCode({
        fontFamily: typefaceValue,
        typeScaleVar: '$type-scale',
        indent,
      }),
    );
    if (addComments) lines.push('');
  }

  // Spacing mixin
  if (includeSpacing) {
    if (addComments) lines.push(`${indent}// Apply spacing CSS variables`);
    lines.push(`${indent}@include spacing();`);
  }

  return lines;
}

/**
 * Generate a custom palette theme with a theme() mixin wrapper.
 */
function generateCustomPaletteTheme(
  template: WebComponentsThemeTemplate,
  typefaceValue: string,
): string[] {
  const {
    designSystem,
    variant,
    primaryColor,
    secondaryColor,
    surfaceColor,
    grayColor,
    customPaletteName = '$my-palette',
    includeTypography = true,
    includeElevations = true,
    includeSpacing = true,
  } = template;

  const lines: string[] = [];

  // Get default colors from the preset
  const presetName = `${variant}-${designSystem}-palette` as PalettePresetName;
  const presetColors = PALETTE_PRESETS[presetName];

  const effectivePrimary = primaryColor || presetColors.primary;
  const effectiveSecondary = secondaryColor || presetColors.secondary;
  const effectiveSurface = surfaceColor || presetColors.surface;

  // Generate palette code
  const paletteResult = generatePaletteCode({
    primary: effectivePrimary,
    secondary: effectiveSecondary,
    surface: effectiveSurface,
    gray: grayColor,
    variableName: customPaletteName.replace(/^\$/, ''),
    useVariableReferences: true,
  });

  lines.push('// Custom color palette');
  lines.push(...paletteResult.colorVariables);
  lines.push('');
  lines.push(...paletteResult.paletteDefinition);
  lines.push('');

  // Generate theme() mixin wrapper
  lines.push('// Theme configuration');
  lines.push('@mixin theme($palette, $variant) {');
  lines.push('  // Root-level CSS custom properties');
  lines.push(...generateWCProgressProperties('  '));
  lines.push('');
  lines.push(...generateWCRootVariables({designSystem, variant, usePaletteMap: true, indent: '  '}));
  lines.push('');
  lines.push(...generateWCRtlSupport('  '));
  lines.push('');
  lines.push(
    ...generateWCThemingMixins({
      paletteVar: '$palette',
      typefaceValue,
      elevationsVar: getWCElevationPreset(designSystem),
      includeTypography,
      includeElevations,
      includeSpacing,
      indent: '  ',
    }),
  );
  lines.push('}');
  lines.push('');
  lines.push('// Apply the theme');
  lines.push(`@include theme(${paletteResult.variableName}, '${variant}');`);

  return lines;
}

/**
 * Generate a preset palette theme (uses predefined palette from design system).
 */
function generatePresetPaletteTheme(
  template: WebComponentsThemeTemplate,
  typefaceValue: string,
): string[] {
  const {designSystem, variant, includeTypography = true, includeElevations = true, includeSpacing = true} = template;

  const lines: string[] = [];

  // Scrollbar customization (uses color() function from palette preset)
  lines.push(...generateWCScrollbarCustomization());
  lines.push('');

  // Progress properties at root level
  lines.push(...generateWCProgressProperties());
  lines.push('');

  // Root variables
  lines.push(...generateWCRootVariables({designSystem, variant}));
  lines.push('');

  // RTL support
  lines.push(...generateWCRtlSupport());
  lines.push('');

  // Theming mixins with comments
  lines.push(
    ...generateWCThemingMixins({
      paletteVar: '$palette',
      typefaceValue,
      elevationsVar: getWCElevationPreset(designSystem),
      includeTypography,
      includeElevations,
      includeSpacing,
      addComments: true,
    }),
  );

  return lines;
}

/**
 * Generate Sass code for a Web Components theme
 *
 * Web Components themes use igniteui-theming directly and call individual
 * mixins (palette, typography, elevations) rather than a unified theme() mixin.
 *
 * This function orchestrates smaller helper functions for:
 * - Header generation (generateWCHeader)
 * - Import statements (generateWCImports)
 * - Custom or preset palette themes
 */
export function generateWebComponentsThemeSass(template: WebComponentsThemeTemplate): string {
  const {
    designSystem,
    variant,
    primaryColor,
    secondaryColor,
    surfaceColor,
    fontFamily,
    includeTypography = true,
    includeElevations = true,
  } = template;

  // Determine the font-family value to use
  const typefaceValue = fontFamily ? quoteFontFamily(fontFamily) : '$typeface';

  // Determine if using custom or preset palette
  const hasCustomColors = !!(primaryColor || secondaryColor || surfaceColor);

  // Build the output
  const lines: string[] = [];

  // Header
  lines.push(...generateWCHeader());

  // Import statements
  lines.push(
    ...generateWCImports({
      designSystem,
      variant,
      hasCustomColors,
      includeTypography,
      includeElevations,
    }),
  );
  lines.push('');

  // Theme body (custom or preset)
  if (hasCustomColors) {
    lines.push(...generateCustomPaletteTheme(template, typefaceValue));
  } else {
    lines.push(...generatePresetPaletteTheme(template, typefaceValue));
  }

  return lines.join('\n');
}

/**
 * Example usage documentation
 */
export const WEBCOMPONENTS_USAGE_EXAMPLES = {
  basic: `
// Basic Material Light Theme for Web Components
@use 'igniteui-theming/sass/color/presets/light/material' as *;
@use 'igniteui-theming' as *;
@use 'igniteui-theming/sass/typography/presets/material' as *;
@use 'igniteui-theming/sass/elevations/presets' as *;

:root {
  --ig-theme: material;
  --ig-theme-variant: light;
  --ig-size-small: 1;
  --ig-size-medium: 2;
  --ig-size-large: 3;
  --ig-scrollbar-size: #{rem(16px)};
}

@include palette($palette);
@include elevations($material-elevations);
@include typography(
  $font-family: $typeface,
  $type-scale: $type-scale
);
@include spacing();
`,

  customPalette: `
// Custom Palette Theme for Web Components
@use 'igniteui-theming' as *;
@use 'igniteui-theming/sass/typography/presets/material' as *;
@use 'igniteui-theming/sass/elevations/presets' as *;

$my-palette: palette(
  $primary: #2ab759,
  $secondary: #f96a88,
  $surface: #ffffff
);

:root {
  --ig-theme: material;
  --ig-theme-variant: light;
  --ig-size-small: 1;
  --ig-size-medium: 2;
  --ig-size-large: 3;
}

@include palette($my-palette);
@include elevations($material-elevations);
@include typography(
  $font-family: $typeface,
  $type-scale: $type-scale
);
@include spacing();
`,

  darkTheme: `
// Dark Indigo Theme for Web Components
@use 'igniteui-theming/sass/color/presets/dark/indigo' as *;
@use 'igniteui-theming' as *;
@use 'igniteui-theming/sass/typography/presets/indigo' as *;
@use 'igniteui-theming/sass/elevations/presets' as *;

:root {
  --ig-theme: indigo;
  --ig-theme-variant: dark;
  --ig-size-small: 1;
  --ig-size-medium: 2;
  --ig-size-large: 3;
}

@include palette($palette);
@include elevations($indigo-elevations);
@include typography(
  $font-family: $typeface,
  $type-scale: $type-scale
);
@include spacing();
`,

  minimalConfig: `
// Minimal theme (palette only, no typography/elevations)
@use 'igniteui-theming/sass/color/presets/light/bootstrap' as *;
@use 'igniteui-theming' as *;

:root {
  --ig-theme: bootstrap;
  --ig-theme-variant: light;
}

@include palette($palette);
`,
} as const;

/**
 * Runtime theme configuration for Web Components
 *
 * Web Components support runtime theme switching via the configureTheme() function
 * and CSS variables. This is different from Angular which requires Sass recompilation.
 */
export const WEBCOMPONENTS_RUNTIME_CONFIG = {
  /**
   * JavaScript API for runtime theme switching
   */
  configureThemeAPI: `
import { configureTheme } from 'igniteui-webcomponents';

// Switch to dark material theme at runtime
configureTheme('material', 'dark');

// Switch to light indigo theme
configureTheme('indigo', 'light');
`,

  /**
   * CSS variables that control the theme at runtime
   */
  runtimeVariables: ['--ig-theme', '--ig-theme-variant'],

  /**
   * Events dispatched during theme changes
   */
  themeChangeEvents: ['igc-change-theme', 'igc-changed-theme'],
} as const;
