/**
 * The palettes the library ships, each one twice: as it ships today, and regenerated by
 * the fitted generator from the seeds it already records.
 *
 * The comparison is only honest if both sides start from the same place, so the seeds
 * are read out of the shipped palette rather than transcribed — what ships is what the
 * legacy side shows, and the fitted side starts from exactly those seeds.
 */
import {
  ACCENTS,
  FAMILIES,
  type Family,
  PRESETS,
  type PresetKey,
  ROLES,
  SHADES,
  THEMES,
  type Theme,
} from "../../variants.js";
import { defineProvider } from "../provider.js";
import { register } from "../registry.js";
import { COLOR_SASS, compile, HEX_FN, HEX_USE } from "./sass-util.js";

export interface PresetSide {
  /** `--ig-*` declarations, ready to apply to a subtree. */
  vars: Record<string, string>;
  /** Resolved literals keyed `family-variant`, for measuring. */
  values: Record<string, string>;
}

export interface Preset {
  key: PresetKey;
  label: string;
  theme: Theme;
  /** What the shipped palette records as each family's seed. */
  seeds: Record<Family, string>;
  legacy: PresetSide;
  fitted: PresetSide;
}

export interface PresetData {
  presets: Preset[];
  /** Sass warnings raised while compiling, reported by the plugin on every serve. */
  warnings: string[];
}

type Generator = "legacy" | "fitted";

/** The variants a family exposes. Surface has roles under fitted and numbers under legacy. */
const variants = (family: Family, generator: Generator): readonly string[] => {
  if (family !== "surface") return [...SHADES, ...ACCENTS];
  return generator === "fitted" ? ROLES : SHADES;
};

/** One rule per preset and side, plus the seeds: `.p-light-material-l { --ig-...: ...; }` */
const probe = (key: PresetKey, theme: Theme) => {
  const cls = `${theme}-${key}`;
  const shipped = `$${theme}-${key}-palette`;
  const sides: [Generator, string][] = [
    ["legacy", shipped],
    ["fitted", `_fit(${shipped})`],
  ];

  return [
    // `_fit()` builds a whole palette, so it is bound once per rule. Calling it inside
    // each lookup would regenerate it sixty times over.
    ...sides.map(
      ([generator, palette]) =>
        `.p-${cls}-${generator} { $s: ${palette}; @include palette($s); }`,
    ),
    `seed-${cls} { ${FAMILIES.map((f) => `${f}: '#{_hex(_seed(${shipped}, "${f}"))}';`).join(" ")} }`,
    ...sides.map(([generator, palette]) => {
      const rows = FAMILIES.flatMap((family) =>
        variants(family, generator).map(
          (v) =>
            `  ${family}-${v}: '#{_lit(map.get(map.get($s, "${family}"), "${v}-raw"))}';`,
        ),
      );
      return `val-${cls}-${generator} {\n  $s: ${palette};\n${rows.join("\n")}\n}`;
    }),
  ].join("\n");
};

const PRELUDE =
  `@use 'sass:map';\n@use 'sass/color' as *;\n@use 'sass/color/presets' as *;\n` +
  HEX_USE +
  `@function _seed($p, $f) { @return map.get(map.get($p, $f), 'seed'); }\n` +
  HEX_FN +
  "@function _fit($p) {\n  @return palette(\n" +
  FAMILIES.map((f) => `    $${f}: _seed($p, '${f}')`).join(",\n") +
  "\n  );\n}\n";

/** Custom property declarations of every rule with this class. */
const declarations = (css: string, selector: string) => {
  const out: Record<string, string> = {};

  for (const [, name, body] of css.matchAll(/\.([\w-]+)\s*\{([^}]*)\}/g)) {
    if (name !== selector) continue;

    for (const [, prop, value] of body.matchAll(/(--[\w-]+):\s*([^;]+);/g)) {
      out[prop] = value.trim();
    }
  }

  return out;
};

/** The quoted `name: "value"` pairs of a probe rule. */
const quoted = <K extends string>(css: string, selector: string) => {
  const rule = css.match(new RegExp(`${selector}\\s*\\{([^}]*)\\}`));
  if (!rule) throw new Error(`presets: missing ${selector}`);

  return Object.fromEntries(
    [...rule[1].matchAll(/([\w-]+):\s*"([^"]*)"/g)].map(([, name, value]) => [
      name,
      value,
    ]),
  ) as Record<K, string>;
};

export const presetData = defineProvider<PresetData>({
  id: "color.presets",
  module: import.meta.url,
  deps: [COLOR_SASS],
  build() {
    const selections = PRESETS.flatMap((preset) =>
      THEMES.map((theme) => ({ ...preset, theme })),
    );
    const { css, warnings } = compile(
      PRELUDE + selections.map((s) => probe(s.key, s.theme)).join("\n"),
    );

    const side = (cls: string, generator: Generator): PresetSide => ({
      vars: declarations(css, `p-${cls}-${generator}`),
      values: quoted(css, `val-${cls}-${generator}`),
    });

    return {
      warnings,
      presets: selections.map(({ key, label, theme }) => {
        const cls = `${theme}-${key}`;

        return {
          key,
          label,
          theme,
          seeds: quoted<Family>(css, `seed-${cls}`),
          legacy: side(cls, "legacy"),
          fitted: side(cls, "fitted"),
        };
      }),
    };
  },
});

register(presetData);
