import { exec as _exec } from "node:child_process";
import { mkdirSync as makeDir, readdirSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import * as sass from "sass-embedded";
import { parseCSS } from "./parser.mjs";
import report from "./report.mjs";

const exec = promisify(_exec);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(__dirname, "..");
const SASS_JSON_DIR = path.join(PACKAGE_ROOT, "sass", "json");
const DIST_DIR = path.resolve(PACKAGE_ROOT, "dist");
const DEST_DIR = path.join.bind(null, path.join(DIST_DIR, "json"));

/**
 * Static mapping of JSON file paths (relative to dist/json/, without extension)
 * to their barrel export names.
 *
 * Update this map when adding or removing JSON outputs.
 */
const EXPORT_MAP = {
  "colors/meta/multipliers": "PaletteMultipliers",
  "colors/meta/palette": "PaletteMeta",
  "colors/presets/palettes": "Palettes",
  "components/bootstrap": "BootstrapThemes",
  "components/fluent": "FluentThemes",
  "components/indigo": "IndigoThemes",
  "components/material": "MaterialThemes",
  "components/themes": "ComponentThemes",
  "elevations/indigo": "IndigoElevations",
  "elevations/material": "MaterialElevations",
  "typography/presets/typescales": "Typescales",
};

/**
 * Generates dist/index.js — a barrel that re-exports all mapped JSON files.
 */
async function generateBarrel() {
  const lines = ["// Auto-generated by buildJSON.mjs — do not edit manually."];

  for (const [jsonPath, exportName] of Object.entries(EXPORT_MAP)) {
    lines.push(
      `export { default as ${exportName} } from './json/${jsonPath}.json' with { type: 'json' };`,
    );
  }

  lines.push("");
  await writeFile(path.join(DIST_DIR, "index.js"), lines.join("\n"), "utf-8");
}

(async () => {
  const start = performance.now();
  const compiler = await sass.initAsyncCompiler();

  await exec("npm run clean:json");
  report.info("Building JSON files...");

  // Generate JSON files from Sass
  const scssFiles = readdirSync(SASS_JSON_DIR)
    .filter((f) => f.endsWith(".scss"))
    .map((f) => path.join(SASS_JSON_DIR, f));

  for (const src of scssFiles) {
    const { css } = await compiler.compileAsync(src, {
      loadPaths: [path.join(PACKAGE_ROOT, "sass")],
      silenceDeprecations: ["color-functions"],
    });

    for (const [out, data] of Object.entries(await parseCSS(css))) {
      const outputFile = DEST_DIR(`${out}.json`);
      makeDir(path.dirname(outputFile), { recursive: true });
      await writeFile(outputFile, JSON.stringify(data), "utf-8");
    }
  }

  // Generate barrel export file
  makeDir(DIST_DIR, { recursive: true });
  await generateBarrel();

  report.success(
    `Built JSON in ${((performance.now() - start) / 1000).toFixed(2)}s`,
  );
  compiler.dispose();
})();
