/**
 * Validates all JSON build artifacts against their Zod schemas, then generates:
 * - dist/index.js  — barrel re-exporting all JSON data as named exports
 * - dist/index.d.ts — TypeScript declarations inferred from the Zod schemas
 *
 * Run this AFTER buildJSON.mjs and buildComponentDocs.mjs have completed.
 */
import { mkdirSync as makeDir, readFileSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { EXPORT_MAP } from "../schemas/index.mjs";
import report from "./report.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(__dirname, "..");
const DIST_DIR = path.resolve(PACKAGE_ROOT, "dist");
const JSON_DIR = path.join(DIST_DIR, "json");

/**
 * Validates all JSON outputs against their Zod schemas.
 * Throws on the first validation error.
 */
function validate() {
  for (const [jsonPath, { exportName, schema }] of Object.entries(EXPORT_MAP)) {
    const filePath = path.join(JSON_DIR, `${jsonPath}.json`);
    const data = JSON.parse(readFileSync(filePath, "utf-8"));
    const result = schema.safeParse(data);

    if (!result.success) {
      const issues = result.error.issues
        .map((i) => `  ${i.path.join(".")}: ${i.message}`)
        .join("\n");
      throw new Error(
        `Schema validation failed for ${exportName} (${jsonPath}.json):\n${issues}`,
      );
    }
  }
}

/**
 * Generates dist/index.js — a barrel that re-exports all mapped JSON files.
 */
async function generateBarrel() {
  const lines = [
    "// Auto-generated by buildBarrel.mjs — do not edit manually.",
  ];

  for (const [jsonPath, { exportName }] of Object.entries(EXPORT_MAP)) {
    lines.push(
      `export { default as ${exportName} } from './json/${jsonPath}.json' with { type: 'json' };`,
    );
  }

  lines.push("");
  await writeFile(path.join(DIST_DIR, "index.js"), lines.join("\n"), "utf-8");
}

/**
 * Generates dist/index.d.ts — type declarations inferred from Zod schemas.
 */
async function generateTypes() {
  const lines = [
    "// Auto-generated by buildBarrel.mjs — do not edit manually.",
    "",
  ];

  for (const [, { exportName, schema }] of Object.entries(EXPORT_MAP)) {
    lines.push(zodSchemaToTS(schema, exportName));
  }

  lines.push("");
  await writeFile(path.join(DIST_DIR, "index.d.ts"), lines.join("\n"), "utf-8");
}

/**
 * Converts a Zod schema to a TypeScript type declaration string.
 */
function zodSchemaToTS(schema, exportName) {
  return `export declare const ${exportName}: ${zodToTSType(schema)};`;
}

/**
 * Recursively converts a Zod schema to a TypeScript type string.
 * Handles the subset of Zod types used in our schemas.
 */
function zodToTSType(schema) {
  if (!schema?._def) return "unknown";

  const def = schema._def;
  const typeName = def.typeName;

  switch (typeName) {
    case "ZodString":
      return "string";

    case "ZodNumber":
      return "number";

    case "ZodBoolean":
      return "boolean";

    case "ZodArray":
      return `${zodToTSType(def.type)}[]`;

    case "ZodOptional":
      return `${zodToTSType(def.innerType)} | undefined`;

    case "ZodRecord": {
      const keyType = def.keyType ? zodToTSType(def.keyType) : "string";
      const valueType = zodToTSType(def.valueType);
      return `Record<${keyType}, ${valueType}>`;
    }

    case "ZodObject": {
      const shape = def.shape?.();
      if (!shape) return "Record<string, unknown>";

      const catchallType =
        def.catchall?._def?.typeName !== "ZodNever"
          ? zodToTSType(def.catchall)
          : null;

      const entries = Object.entries(shape).map(([key, val]) => {
        const optional = val._def?.typeName === "ZodOptional";
        const type = optional
          ? zodToTSType(val._def.innerType)
          : zodToTSType(val);
        return `  ${JSON.stringify(key)}${optional ? "?" : ""}: ${type}`;
      });

      if (catchallType) {
        entries.push(`  [key: string]: ${catchallType}`);
      }

      return `{\n${entries.join(";\n")};\n}`;
    }

    case "ZodEnum":
      return def.values.map((v) => JSON.stringify(v)).join(" | ");

    default:
      return "unknown";
  }
}

// ─── Main ───────────────────────────────────────────────────────────────────

const start = performance.now();

makeDir(DIST_DIR, { recursive: true });
validate();
await generateBarrel();
await generateTypes();

report.success(
  `Validated & generated barrel in ${((performance.now() - start) / 1000).toFixed(2)}s`,
);
