/**
 * CSS code generator for Ignite UI Theming.
 * Generates CSS custom properties (variables) by compiling Sass and extracting the output.
 *
 */

import * as sass from 'sass-embedded';
import * as path from 'path';
import {fileURLToPath} from 'url';
import type {ColorDefinition, GrayDefinition, ThemeVariant} from '../utils/types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// From dist/mcp/generators/ we need to go up 3 levels to package root
const PACKAGE_ROOT = path.resolve(__dirname, '..', '..', '..');

/**
 * Result from generating CSS palette variables.
 */
export interface CssPaletteResult {
  css: string;
  description: string;
}

/**
 * Options for generating standard palette CSS variables.
 */
export interface PaletteCssOptions {
  primary: string;
  secondary: string;
  surface: string;
  gray?: string;
  info?: string;
  success?: string;
  warn?: string;
  error?: string;
  variant?: ThemeVariant;
  _loadPaths?: string[];
}

/**
 * Generate CSS custom properties for a standard palette.
 *
 * This function compiles Sass code that uses the palette() function and
 * @include palette() mixin, then returns the compiled CSS output.
 *
 * @example
 * const result = await generatePaletteCss({
 *   primary: '#1976d2',
 *   secondary: '#ff9800',
 *   surface: '#fafafa',
 *   variant: 'light'
 * });
 * // result.css contains :root { --ig-primary-50: ...; --ig-primary-100: ...; ... }
 */
export async function generatePaletteCss(options: PaletteCssOptions): Promise<CssPaletteResult> {
  const variant = options.variant ?? 'light';

  const paletteArgs: string[] = [
    `$primary: ${options.primary}`,
    `$secondary: ${options.secondary}`,
    `$surface: ${options.surface}`,
  ];

  if (options.gray) paletteArgs.push(`$gray: ${options.gray}`);
  if (options.info) paletteArgs.push(`$info: ${options.info}`);
  if (options.success) paletteArgs.push(`$success: ${options.success}`);
  if (options.warn) paletteArgs.push(`$warn: ${options.warn}`);
  if (options.error) paletteArgs.push(`$error: ${options.error}`);

  const sassCode = `
@use 'sass/color' as *;

$palette: palette(
  ${paletteArgs.join(',\n  ')}
);

@include palette($palette);
`;

  try {
    const loadPaths = options._loadPaths ?? [PACKAGE_ROOT];
    const result = await sass.compileStringAsync(sassCode, {
      loadPaths,
      style: 'expanded',
    });

    return {
      css: result.css,
      description: `Generated CSS custom properties for a ${variant} palette with primary color ${options.primary}`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to compile palette CSS: ${message}`);
  }
}

/**
 * Options for generating custom palette CSS variables.
 */
export interface CustomPaletteCssOptions {
  variant?: ThemeVariant;
  surfaceColor?: string;
  colors: {
    primary: ColorDefinition;
    secondary: ColorDefinition;
    surface: ColorDefinition;
    gray: GrayDefinition;
    info: ColorDefinition;
    success: ColorDefinition;
    warn: ColorDefinition;
    error: ColorDefinition;
  };
  _loadPaths?: string[];
}

/**
 * Generate CSS custom properties for a custom palette.
 *
 * This function generates Sass code for the custom palette structure
 * (using either shades() function or explicit values), compiles it,
 * and returns the CSS output.
 */
export async function generateCustomPaletteCss(options: CustomPaletteCssOptions): Promise<CssPaletteResult> {
  const variant = options.variant ?? 'light';
  const {generateCustomPaletteCode} = await import('../utils/sass.js');

  const paletteLines = generateCustomPaletteCode({
    variant,
    variableName: 'custom',
    surfaceColor: options.surfaceColor,
    colors: options.colors,
  });

  const sassCode = `
@use 'sass/color' as *;

${paletteLines.join('\n')}

@include palette($custom-palette);
`;

  try {
    const loadPaths = options._loadPaths ?? [PACKAGE_ROOT];
    const result = await sass.compileStringAsync(sassCode, {
      loadPaths,
      style: 'expanded',
    });

    return {
      css: result.css,
      description: `Generated CSS custom properties for a custom ${variant} palette`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);

    throw new Error(`Failed to compile custom palette CSS: ${message}`);
  }
}

/**
 * Format CSS output for display.
 * Adds a header comment and ensures consistent formatting.
 */
export function formatCssOutput(css: string, description: string): string {
  const header = `/* Generated by Ignite UI Theming MCP Server */
/* ${description} */
`;
  return header + css;
}
