/**
 * CSS code generator for Ignite UI Theming.
 * Generates CSS custom properties (variables) by compiling Sass and extracting the output.
 *
 */

import type { FileImporter } from "sass-embedded";
import * as sass from "sass-embedded";
import { themingImporter } from "../utils/theming-resolve.js";
import type {
  ColorDefinition,
  GrayDefinition,
  PLATFORMS,
  ThemeVariant,
} from "../utils/types.js";

/**
 * Result from generating CSS palette variables.
 */
export interface CssPaletteResult {
  css: string;
  description: string;
}

/**
 * Result from generating component theme CSS.
 */
export interface CssComponentThemeResult {
  css: string;
  description: string;
}

/**
 * Options for generating standard palette CSS variables.
 */
export interface PaletteCssOptions {
  primary: string;
  secondary: string;
  surface: string;
  gray?: string;
  info?: string;
  success?: string;
  warn?: string;
  error?: string;
  variant?: ThemeVariant;
  /** Internal testing parameter for Sass importers */
  _importers?: FileImporter[];
}

/**
 * Generate CSS custom properties for a standard palette.
 *
 * This function compiles Sass code that uses the palette() function and
 * @include palette() mixin, then returns the compiled CSS output.
 *
 * @example
 * const result = await generatePaletteCss({
 *   primary: '#1976d2',
 *   secondary: '#ff9800',
 *   surface: '#fafafa',
 *   variant: 'light'
 * });
 * // result.css contains :root { --ig-primary-50: ...; --ig-primary-100: ...; ... }
 */
export async function generatePaletteCss(
  options: PaletteCssOptions,
): Promise<CssPaletteResult> {
  const variant = options.variant ?? "light";

  const paletteArgs: string[] = [
    `$primary: ${options.primary}`,
    `$secondary: ${options.secondary}`,
    `$surface: ${options.surface}`,
  ];

  if (options.gray) paletteArgs.push(`$gray: ${options.gray}`);
  if (options.info) paletteArgs.push(`$info: ${options.info}`);
  if (options.success) paletteArgs.push(`$success: ${options.success}`);
  if (options.warn) paletteArgs.push(`$warn: ${options.warn}`);
  if (options.error) paletteArgs.push(`$error: ${options.error}`);

  const sassCode = `
@use 'igniteui-theming/sass/color' as *;

$palette: palette(
  ${paletteArgs.join(",\n  ")}
);

@include palette($palette);
`;

  try {
    const importers = options._importers ?? [themingImporter];
    const result = await sass.compileStringAsync(sassCode, {
      importers,
      style: "expanded",
    });

    return {
      css: result.css,
      description: `Generated CSS custom properties for a ${variant} palette with primary color ${options.primary}`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to compile palette CSS: ${message}`);
  }
}

/**
 * Options for generating custom palette CSS variables.
 */
export interface CustomPaletteCssOptions {
  variant?: ThemeVariant;
  surfaceColor?: string;
  colors: {
    primary: ColorDefinition;
    secondary: ColorDefinition;
    surface: ColorDefinition;
    gray: GrayDefinition;
    info: ColorDefinition;
    success: ColorDefinition;
    warn: ColorDefinition;
    error: ColorDefinition;
  };
  /** Internal testing parameter for Sass importers */
  _importers?: FileImporter[];
}

/**
 * Generate CSS custom properties for a custom palette.
 *
 * This function generates Sass code for the custom palette structure
 * (using either shades() function or explicit values), compiles it,
 * and returns the CSS output.
 */
export async function generateCustomPaletteCss(
  options: CustomPaletteCssOptions,
): Promise<CssPaletteResult> {
  const variant = options.variant ?? "light";
  const { generateCustomPaletteCode } = await import("../utils/sass.js");

  const paletteLines = generateCustomPaletteCode({
    variant,
    variableName: "custom",
    surfaceColor: options.surfaceColor,
    colors: options.colors,
  });

  const sassCode = `
@use 'igniteui-theming/sass/color' as *;

${paletteLines.join("\n")}

@include palette($custom-palette);
`;

  try {
    const importers = options._importers ?? [themingImporter];
    const result = await sass.compileStringAsync(sassCode, {
      importers,
      style: "expanded",
    });

    return {
      css: result.css,
      description: `Generated CSS custom properties for a custom ${variant} palette`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);

    throw new Error(`Failed to compile custom palette CSS: ${message}`);
  }
}

/**
 * Format CSS output for display.
 * Adds a header comment and ensures consistent formatting.
 */
export function formatCssOutput(css: string, description: string): string {
  const header = `/* Generated by Ignite UI Theming MCP Server */
/* ${description} */
`;
  return header + css;
}

/**
 * Options for generating component theme CSS variables.
 */
export interface ComponentThemeCssOptions {
  platform: (typeof PLATFORMS)[number];
  /** Design system (defaults to 'material') */
  designSystem?: string;
  /** Theme variant - light or dark (defaults to 'light') */
  variant?: string;
  /** Component name (e.g., "button", "avatar") */
  component: string;
  /** Token name-value pairs */
  tokens: Record<string, string | number>;
  /** CSS selector to scope the theme (optional) */
  selector?: string;
  /** Custom variable name (optional) */
  name?: string;
  /** Internal testing parameter for Sass importers */
  _importers?: FileImporter[];
}

/**
 * Generate CSS custom properties for a component theme.
 *
 * This function compiles Sass code that uses the component theme function
 * and @include tokens() mixin, then returns the compiled CSS output.
 *
 * @example
 * const result = await generateComponentThemeCss({
 *   platform: 'webcomponents',
 *   designSystem: 'bootstrap',
 *   variant: 'light',
 *   component: 'button',
 *   tokens: { background: '#1976d2', 'text-color': 'white' },
 *   selector: 'igc-button'
 * });
 * // result.css contains: igc-button { --ig-button-background: var(--ig-button-background, #1976d2); ... }
 */
export async function generateComponentThemeCss(
  options: ComponentThemeCssOptions,
): Promise<CssComponentThemeResult> {
  // Import functions we need (dynamic import to avoid circular dependencies)
  const {
    COMPONENT_METADATA,
    getComponentTheme,
    getThemingSelector,
    SCHEMA_PRESETS,
  } = await import("../knowledge/index.js");
  const { toVariableName } = await import("../utils/sass.js");

  // Validate component exists
  const theme = getComponentTheme(options.component);

  if (!theme) {
    throw new Error(`Unknown component: ${options.component}`);
  }

  const designSystem = options.designSystem ?? "material";
  const variant = options.variant ?? "light";
  const themeFn = theme.themeFunctionName;
  // For child components, derive variable name from parent
  const themeComponentName =
    COMPONENT_METADATA[options.component]?.childOf ?? options.component;
  const themeName = options.name
    ? `$${toVariableName(options.name)}`
    : `$custom-${themeComponentName}-theme`;

  // Get the schema variable based on design system and variant
  const schemaVar =
    SCHEMA_PRESETS[variant as "light" | "dark"][
      designSystem as "material" | "indigo" | "bootstrap" | "fluent"
    ];

  // Build token arguments - schema comes first
  const tokenArgs: string[] = [`$schema: ${schemaVar}`];

  for (const [tokenName, value] of Object.entries(options.tokens)) {
    const stringValue = typeof value === "number" ? String(value) : value;
    tokenArgs.push(`$${tokenName}: ${stringValue}`);
  }

  // Determine selector - use platform-specific theming selector as default
  // For child components, this resolves to the parent's selector
  const defaultSelectors = getThemingSelector(
    options.component,
    options.platform,
  );
  const selector =
    options.selector ||
    (defaultSelectors.length > 0 ? defaultSelectors[0] : options.component);

  // Generate Sass code
  const sassCode = `
@use 'igniteui-theming/sass/themes' as *;
@use 'igniteui-theming/sass/themes/schemas' as *;

// Custom ${themeComponentName} theme
${themeName}: ${themeFn}(
  ${tokenArgs.join(",\n  ")}
);

// Apply the theme to ${selector}
${selector} {
  @include tokens(${themeName});
}
`;

  try {
    const importers = options._importers ?? [themingImporter];
    const result = await sass.compileStringAsync(sassCode, {
      importers,
      style: "expanded",
    });

    return {
      css: result.css,
      description: `Generated CSS custom properties for ${themeComponentName} component with ${Object.keys(options.tokens).length} token(s) using ${designSystem} design system (${variant} variant)`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to compile component theme CSS: ${message}`);
  }
}

// ============================================================================
// Typography, Elevations, and Theme CSS generators
// ============================================================================

/**
 * Options for generating typography CSS variables.
 */
export interface TypographyCssOptions {
  /** Font family string with fallbacks */
  fontFamily?: string;
  /** Design system preset (defaults to 'material') */
  designSystem?: string;
  /** Internal testing parameter for Sass importers */
  _importers?: FileImporter[];
}

/**
 * Generate CSS custom properties for a typography setup.
 *
 * Compiles the typography() mixin and returns the resulting CSS custom
 * properties (--ig-h1-font-size, --ig-body-1-font-weight, etc.).
 */
export async function generateTypographyCss(
  options: TypographyCssOptions,
): Promise<CssPaletteResult> {
  const { TYPOGRAPHY_PRESETS } = await import("../knowledge/typography.js");
  const { quoteFontFamily } = await import("../utils/sass.js");

  const designSystem = options.designSystem ?? "material";
  const preset =
    TYPOGRAPHY_PRESETS[designSystem as keyof typeof TYPOGRAPHY_PRESETS];
  const typeface =
    options.fontFamily || (preset as any)?.typeface || "Roboto, sans-serif";
  const typeScaleVar = `$${designSystem}-type-scale`;

  const sassCode = `
@use 'igniteui-theming/sass/typography' as *;
@use 'igniteui-theming/sass/typography/presets' as *;

@include typography(
  $font-family: ${quoteFontFamily(typeface)},
  $type-scale: ${typeScaleVar}
);
`;

  try {
    const importers = options._importers ?? [themingImporter];
    const result = await sass.compileStringAsync(sassCode, {
      importers,
      style: "expanded",
    });

    return {
      css: result.css,
      description: `Generated CSS custom properties for typography using ${designSystem} type scale with font family ${typeface}`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to compile typography CSS: ${message}`);
  }
}

/**
 * Options for generating elevations CSS variables.
 */
export interface ElevationsCssOptions {
  /** Design system preset: 'material' or 'indigo' (defaults to 'material') */
  designSystem?: string;
  /** Internal testing parameter for Sass importers */
  _importers?: FileImporter[];
}

/**
 * Generate CSS custom properties for elevations.
 *
 * Compiles the elevations() mixin and returns the resulting CSS custom
 * properties (--ig-elevation-0 through --ig-elevation-24).
 */
export async function generateElevationsCss(
  options: ElevationsCssOptions,
): Promise<CssPaletteResult> {
  const preset = options.designSystem ?? "material";
  const elevationsVar = `$${preset}-elevations`;

  const sassCode = `
@use 'igniteui-theming/sass/elevations' as *;
@use 'igniteui-theming/sass/elevations/presets' as *;

@include elevations(${elevationsVar});
`;

  try {
    const importers = options._importers ?? [themingImporter];
    const result = await sass.compileStringAsync(sassCode, {
      importers,
      style: "expanded",
    });

    return {
      css: result.css,
      description: `Generated CSS custom properties for elevations using ${preset} preset (25 elevation levels)`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to compile elevations CSS: ${message}`);
  }
}

/**
 * Options for generating a complete theme's CSS variables.
 */
export interface ThemeCssOptions {
  platform?: (typeof PLATFORMS)[number];
  designSystem?: string;
  variant?: ThemeVariant;
  primaryColor: string;
  secondaryColor: string;
  surfaceColor: string;
  fontFamily?: string;
  includeTypography?: boolean;
  includeElevations?: boolean;
  includeSpacing?: boolean;
  name?: string;
  /** Internal testing parameter for Sass importers */
  _importers?: FileImporter[];
}

/**
 * Result from generating a complete theme's CSS variables.
 */
export interface CssThemeResult {
  css: string;
  description: string;
  /**
   * True when platform is 'angular'. Angular CSS output contains only
   * CSS custom properties — it does not include the component-scoped class
   * styles generated by Angular's core() and theme() mixins.
   */
  angularCaveat?: boolean;
}

/**
 * Generate CSS custom properties for a complete theme.
 *
 * For Web Components, React, and Blazor this compiles the full
 * palette + typography + elevations Sass and returns all resulting
 * CSS custom properties in one block.
 *
 * For Angular the same approach is used, but the response carries
 * `angularCaveat: true` to signal that component-scoped class styles
 * (generated by core() + theme()) are absent from the CSS output.
 */
export async function generateThemeCss(
  options: ThemeCssOptions,
): Promise<CssThemeResult> {
  const { TYPOGRAPHY_PRESETS } = await import("../knowledge/typography.js");
  const { quoteFontFamily, toVariableName } = await import("../utils/sass.js");

  const designSystem = options.designSystem ?? "material";
  const variant = options.variant ?? "light";
  const isAngular = options.platform === "angular";
  const paletteName = options.name
    ? `$${toVariableName(options.name)}-palette`
    : "$palette";

  const includeTypography = options.includeTypography !== false;
  const includeElevations = options.includeElevations !== false;
  const includeSpacing = options.includeSpacing !== false;

  const preset =
    TYPOGRAPHY_PRESETS[designSystem as keyof typeof TYPOGRAPHY_PRESETS];
  const typeface =
    options.fontFamily || (preset as any)?.typeface || "Roboto, sans-serif";
  const typeScaleVar = `$${designSystem}-type-scale`;
  const elevationsVar =
    designSystem === "indigo" ? "$indigo-elevations" : "$material-elevations";

  // Build imports using explicit sub-module paths resolvable by themingImporter
  const importLines: string[] = ["@use 'igniteui-theming/sass/color' as *;"];
  if (includeTypography) {
    importLines.push("@use 'igniteui-theming/sass/typography' as *;");
    importLines.push("@use 'igniteui-theming/sass/typography/presets' as *;");
  }
  if (includeElevations) {
    importLines.push("@use 'igniteui-theming/sass/elevations' as *;");
    importLines.push("@use 'igniteui-theming/sass/elevations/presets' as *;");
  }
  if (includeSpacing) {
    importLines.push("@use 'igniteui-theming/sass/themes' as *;");
  }

  const mixinLines: string[] = [];
  mixinLines.push(`@include palette(${paletteName});`);
  if (includeElevations) {
    mixinLines.push(`@include elevations(${elevationsVar});`);
  }
  if (includeTypography) {
    mixinLines.push(
      `@include typography(\n  $font-family: ${quoteFontFamily(typeface)},\n  $type-scale: ${typeScaleVar}\n);`,
    );
  }
  if (includeSpacing) {
    mixinLines.push("@include spacing();");
  }

  const sassCode = `
${importLines.join("\n")}

${paletteName}: palette(
  $primary: ${options.primaryColor},
  $secondary: ${options.secondaryColor},
  $surface: ${options.surfaceColor}
);

${mixinLines.join("\n")}
`;

  try {
    const importers = options._importers ?? [themingImporter];
    const result = await sass.compileStringAsync(sassCode, {
      importers,
      style: "expanded",
    });

    return {
      css: result.css,
      description: `Generated CSS custom properties for a complete ${variant} ${designSystem} theme`,
      angularCaveat: isAngular,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to compile theme CSS: ${message}`);
  }
}
