/**
 * Tools index - exports schemas and handlers for all MCP tools.
 */

export {
  handleCreateComponentTheme,
  handleCreateCustomPalette,
  handleCreateElevations,
  handleCreatePalette,
  handleCreateTheme,
  handleCreateTypography,
  handleDetectPlatform,
  handleFitColorScale,
  handleGetChartSeriesColors,
  handleGetColor,
  handleGetComponentDesignTokens,
  handleReadResource,
  handleSetRoundness,
  handleSetSize,
  handleSetSpacing,
} from "./handlers/index.js";
export {
  type CreateComponentThemeParams,
  type CreateCustomPaletteParams,
  type CreateElevationsParams,
  type CreatePaletteParams,
  type CreateThemeParams,
  type CreateTypographyParams,
  createComponentThemeSchema,
  createCustomPaletteSchema,
  createElevationsSchema,
  createPaletteSchema,
  createThemeSchema,
  createTypographySchema,
  type DetectPlatformParams,
  detectPlatformSchema,
  type FitColorScaleParams,
  fitColorScaleSchema,
  type GetChartSeriesColorsParams,
  type GetColorParams,
  type GetComponentDesignTokensParams,
  getChartSeriesColorsSchema,
  getColorSchema,
  getComponentDesignTokensSchema,
  type Platform,
  platformSchema,
  type ReadResourceParams,
  readResourceSchema,
  type SetRoundnessParams,
  type SetSizeParams,
  type SetSpacingParams,
  setRoundnessSchema,
  setSizeSchema,
  setSpacingInputSchema,
  setSpacingSchema,
} from "./schemas.js";
