/**
 * Layout documentation resources for sizing, spacing, and roundness.
 */

export const LAYOUT_OVERVIEW_DOC = [
  '# Layout scale overview',
  '',
  'Ignite UI components expose sizing, spacing, and roundness through CSS custom properties.',
  'You can set them globally on :root or locally on a specific component selector.',
  '',
  '## Size',
  '--ig-size is the primary control. Components map it into --component-size internally:',
  '--component-size: var(--ig-size, <default-size-from-theme>).',
  '',
  'Size affects any styles that use sizable() or pad() functions.',
  'Suggested values:',
  '- 1 = small',
  '- 2 = medium (default in mosts components)',
  '- 3 = large',
  '- fractional values are NOT ALLOWED (0.75, 1.5)',
  '',
  '## Spacing',
  '--ig-spacing scales spacing used by pad(), pad-inline(), and pad-block().',
  'Suggested values:',
  '- 0 = no spacing',
  '- 1 = default',
  '- 2 = double',
  '- fractional values are ALLOWED (0.75, 1.5)',
  '',
  'You can override inline or block independently:',
  '- --ig-spacing-inline',
  '- --ig-spacing-block',
  '',
  '## Roundness',
  '--ig-radius-factor scales border radius values when border-radius() is used.',
  '- 0 = minimum radius',
  '- 1 = maximum radius',
  '- values between 0 and 1 interpolate between min and max',
  '',
  '## Examples',
  '',
  '### CSS (global)',
  '```css',
  ':root {',
  '  --ig-size: 2;',
  '  --ig-spacing: 0.75;',
  '  --ig-radius-factor: 0.8;',
  '}',
  '```',
  '',
  '### CSS (component scope)',
  '```css',
  'igx-calendar,',
  'igc-calendar {',
  '  --ig-size: 1;',
  '  --ig-spacing: 0.5;',
  '  --ig-radius-factor: 0.9;',
  '}',
  '```',
  '',
  '### Sass notes',
  '- To react to --ig-size, component styles must include @include sizable().',
  '- To use pad(), pad-inline(), or pad-block(), include @include spacing() once.',
  '- border-radius() responds to --ig-radius-factor without extra mixins.',
].join('\n');

export const PAD_FUNCTION_DOC = [
  '# pad() function',
  '',
  'Returns a size-aware spacing value based on --ig-spacing and size flags.',
  '',
  '## Mechanism',
  'pad() uses --is-small/medium/large (from @include sizable()) and multiplies the',
  'chosen size by spacing variables:',
  '- --ig-spacing',
  '- --ig-spacing-inline (optional)',
  '- --ig-spacing-block (optional)',
  '',
  '## Sass example',
  '```scss',
  '.my-card {',
  '  padding: pad(4px, 8px, 16px);',
  '}',
  '```',
  '',
  '## CSS example',
  '```css',
  '.my-card {',
  '  --ig-spacing: 0.75;',
  '}',
  '```',
  '',
  '## Notes',
  '- Requires @include sizing() and @include sizable() in component styles.',
  '- Requires @include spacing() once to set spacing variables.',
].join('\n');

export const SIZABLE_FUNCTION_DOC = [
  '# sizable() function',
  '',
  'Returns a size-aware value based on --ig-size and --component-size.',
  '',
  '## Mechanism',
  'sizable() chooses between small/medium/large values using:',
  '- --component-size (resolved from --ig-size)',
  '- --ig-size-small/medium/large',
  '- --is-small/medium/large from @include sizable()',
  '',
  '## Sass example',
  '```scss',
  '.my-avatar {',
  '  width: sizable(32px, 40px, 48px);',
  '  height: sizable(32px, 40px, 48px);',
  '}',
  '```',
  '',
  '## CSS example',
  '```css',
  ':root {',
  '  --ig-size: 2;',
  '}',
  '```',
  '',
  '## Notes',
  '- Requires @include sizable() in component styles.',
].join('\n');

export const BORDER_RADIUS_FUNCTION_DOC = [
  '# border-radius() function',
  '',
  'Clamps a radius value between min and max using --ig-radius-factor (0 to 1).',
  '',
  '## Mechanism',
  'border-radius() calculates:',
  'clamp(min, calc(var(--ig-radius-factor) * max), max)',
  '',
  '## Sass example',
  '```scss',
  '.my-pill {',
  '  border-radius: border-radius(16px, 4px, 20px);',
  '}',
  '```',
  '',
  '## CSS example',
  '```css',
  '.my-pill {',
  '  --ig-radius-factor: 0.8;',
  '}',
  '```',
  '',
  '## Notes',
  '- Works without additional mixins.',
].join('\n');

export const SPACING_MIXIN_DOC = [
  '# spacing() mixin',
  '',
  'Defines spacing custom properties used by pad(), pad-inline(), and pad-block().',
  '',
  '## Sass example',
  '```scss',
  '@include spacing();',
  '```',
  '',
  '## CSS example',
  '```css',
  ':root {',
  '  --ig-spacing: 1;',
  '  --ig-spacing-inline: 0.75;',
  '  --ig-spacing-block: 0.5;',
  '}',
  '```',
  '',
  '## Notes',
  '- spacing() is typically included once at the root scope.',
].join('\n');

export const SIZING_MIXIN_DOC = [
  '# sizing() mixin',
  '',
  'Defines @property rules for size levels:',
  '- --ig-size-small',
  '- --ig-size-medium',
  '- --ig-size-large',
  '',
  '## Sass example',
  '```scss',
  '@include sizing();',
  '```',
  '',
  '## Notes',
  '- Typically included once at the root scope.',
].join('\n');

export const SIZABLE_MIXIN_DOC = [
  '# sizable() mixin',
  '',
  'Defines size state flags used by sizable() and pad():',
  '- --is-small',
  '- --is-medium',
  '- --is-large',
  '',
  '## Sass example',
  '```scss',
  '.my-component {',
  '  @include sizable();',
  '}',
  '```',
  '',
  '## Notes',
  '- Required for components to react to --ig-size changes.',
].join('\n');
