/**
 * Color shade multipliers used for generating color shades.
 * These are loaded from the JSON files generated by buildJSON.mjs
 * which is the single source of truth from the Sass code.
 */

import multipliersData from '../../../json/colors/meta/multipliers.json' with { type: 'json' };

// Re-export shade level constants and types from the canonical source
export {SHADE_LEVELS, ACCENT_SHADE_LEVELS, type ShadeLevel, type AccentShadeLevel} from '../utils/types.js';

export interface ShadeMultipliers {
  s?: Record<string, string>;
  l: Record<string, string>;
}

/**
 * Multipliers for chromatic colors (primary, secondary, info, success, warn, error).
 * Contains saturation (s) and lightness (l) multipliers for each shade level.
 */
export const COLOR_MULTIPLIERS: ShadeMultipliers = multipliersData.color as ShadeMultipliers;

/**
 * Multipliers for grayscale colors.
 * Only contains lightness (l) multipliers as grayscale has no saturation.
 */
export const GRAYSCALE_MULTIPLIERS: Pick<ShadeMultipliers, 'l'> = multipliersData.grayscale as Pick<ShadeMultipliers, 'l'>;
