/**
 * Embedded palette presets from the Ignite UI Theming framework.
 * These are loaded from the JSON files generated by buildJSON.mjs
 * which is the single source of truth from the Sass code.
 */

import palettesData from '../../../json/colors/presets/palettes.json' with { type: 'json' };

export interface PaletteColors {
  primary: string;
  secondary: string;
  gray: string;
  surface: string;
  info: string;
  success: string;
  warn: string;
  error: string;
}

export type PalettePresetName =
  | 'light-bootstrap-palette'
  | 'dark-bootstrap-palette'
  | 'light-material-palette'
  | 'dark-material-palette'
  | 'light-fluent-palette'
  | 'dark-fluent-palette'
  | 'light-indigo-palette'
  | 'dark-indigo-palette';

/**
 * All palette presets loaded from JSON.
 */
export const PALETTE_PRESETS = palettesData as Record<PalettePresetName, PaletteColors>;

/**
 * Get light palette presets only.
 */
export const LIGHT_PALETTE_PRESETS = {
  'light-bootstrap-palette': PALETTE_PRESETS['light-bootstrap-palette'],
  'light-material-palette': PALETTE_PRESETS['light-material-palette'],
  'light-fluent-palette': PALETTE_PRESETS['light-fluent-palette'],
  'light-indigo-palette': PALETTE_PRESETS['light-indigo-palette'],
} as const;

/**
 * Get dark palette presets only.
 */
export const DARK_PALETTE_PRESETS = {
  'dark-bootstrap-palette': PALETTE_PRESETS['dark-bootstrap-palette'],
  'dark-material-palette': PALETTE_PRESETS['dark-material-palette'],
  'dark-fluent-palette': PALETTE_PRESETS['dark-fluent-palette'],
  'dark-indigo-palette': PALETTE_PRESETS['dark-indigo-palette'],
} as const;

// ============================================================================
// Palette Luminance Guidance
// ============================================================================

/**
 * Documentation about color luminance and shade generation suitability.
 *
 * The theming system uses two different luminance concepts:
 *
 * 1. **LUMINANCE_THRESHOLD (0.5)** - Determines if a color is "light" or "dark"
 *    for variant matching. Used to validate that surface/gray colors match
 *    the theme variant (light themes need light surfaces, dark themes need
 *    dark surfaces).
 *
 * 2. **PALETTE_LUMINANCE_THRESHOLDS** - Determines if a color is suitable for
 *    automatic shade generation with the palette() function:
 *    - TOO_DARK (< 0.05): Lighter shades (50-200) will lack contrast range
 *    - TOO_LIGHT (> 0.45): Darker shades (600-900) will appear washed out
 *    - Ideal range: 0.05 - 0.45 luminance
 *
 * When a color falls outside the ideal range for shade generation, the
 * create_theme tool will warn and recommend using create_custom_palette
 * with explicit shade values instead.
 */
export const PALETTE_LUMINANCE_GUIDANCE = `
## Color Luminance and Shade Generation

### Why Luminance Matters

The palette() function generates 10 shades (50-900) from a base color by
adjusting lightness. This works well when the base color has moderate
luminance, but produces poor results for extreme values:

- **Very light colors (luminance > 0.45)**: The darker shades (600-900)
  will appear washed out because there's limited "darkening room"
- **Very dark colors (luminance < 0.05)**: The lighter shades (50-200)
  will lack contrast range because there's limited "lightening room"

### Ideal Base Color Range

For best results with automatic shade generation:
- **Luminance**: 0.05 - 0.45
- **CIELAB L***: 25 - 73 (approximately)
- **Examples**: Medium blues, greens, purples, oranges work well
- **Problematic**: Near-white (#f5f5f5), near-black (#1a1a1a), pastels

### When to Use create_custom_palette

Use create_custom_palette with explicit shade values when:
1. Base color luminance is outside 0.05-0.45 range
2. Brand guidelines specify exact shades
3. Accessibility requirements need specific contrast ratios
4. You need precise control over the shade progression

### Example: Problematic vs. Ideal Colors

| Color | Luminance | Suitability |
|-------|-----------|-------------|
| #2196F3 | 0.28 | ✅ Ideal - good shade range |
| #4CAF50 | 0.30 | ✅ Ideal - good shade range |
| #FF5722 | 0.18 | ✅ Ideal - good shade range |
| #f5f5f5 | 0.91 | ❌ Too light - use explicit shades |
| #1a1a1a | 0.02 | ❌ Too dark - use explicit shades |
| #e3f2fd | 0.88 | ❌ Too light - use explicit shades |
`;
