/**
 * Typography presets for each design system.
 * These are loaded from the JSON files generated by buildJSON.mjs
 * which is the single source of truth from the Sass code.
 */

import typescalesData from "../../../json/typography/presets/typescales.json" with {
	type: "json",
};
import type { DesignSystem } from "../utils/types.js";

// Re-export DesignSystem for backwards compatibility
export type { DesignSystem } from "../utils/types.js";

export interface TypeStyle {
	"font-family": string;
	"font-size": string;
	"font-weight": string;
	"font-style": string;
	"line-height": string;
	"letter-spacing": string;
	"text-transform": string;
	"margin-top"?: string;
	"margin-bottom"?: string;
}

export interface TypeScale {
	typeface: string;
	h1: TypeStyle;
	h2: TypeStyle;
	h3: TypeStyle;
	h4: TypeStyle;
	h5: TypeStyle;
	h6: TypeStyle;
	"subtitle-1": TypeStyle;
	"subtitle-2": TypeStyle;
	"body-1": TypeStyle;
	"body-2": TypeStyle;
	button: TypeStyle;
	caption: TypeStyle;
	overline: TypeStyle;
}

/**
 * Typography presets loaded from JSON.
 */
export const TYPOGRAPHY_PRESETS = typescalesData as Record<
	DesignSystem,
	TypeScale
>;

/**
 * Type scale category names.
 */
export const TYPE_SCALE_CATEGORIES = [
	"h1",
	"h2",
	"h3",
	"h4",
	"h5",
	"h6",
	"subtitle-1",
	"subtitle-2",
	"body-1",
	"body-2",
	"button",
	"caption",
	"overline",
] as const;

export type TypeScaleCategory = (typeof TYPE_SCALE_CATEGORIES)[number];
