/**
 * Tests for Angular theme generation.
 *
 * Tests verify the generateAngularThemeSass function produces
 * correct Sass code for Ignite UI for Angular applications.
 */

import {describe, it, expect} from 'vitest';
import {generateAngularThemeSass} from '../../knowledge/platforms/angular.js';

describe('generateAngularThemeSass', () => {
  describe('basic theme generation', () => {
    it('generates code with correct header and platform comment', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
      });

      expect(code).toContain('// Generated by Ignite UI Theming MCP Server');
      expect(code).toContain('// Platform: Ignite UI for Angular');
    });

    it('imports igniteui-angular/theming module', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
      });

      expect(code).toContain('@use "igniteui-angular/theming" as *;');
    });

    it('includes core() mixin', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
      });

      expect(code).toContain('@include core()');
    });

    it('includes theme() mixin with palette and schema', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
      });

      expect(code).toContain('@include theme(');
      expect(code).toContain('$palette:');
      expect(code).toContain('$schema:');
    });
  });

  describe('typography handling', () => {
    it('includes typography mixin by default', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
      });

      expect(code).toContain('@include typography(');
    });

    it('uses design system typeface variable', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
      });

      expect(code).toContain('$material-typeface');
      expect(code).toContain('$material-type-scale');
    });

    it('uses indigo typeface for indigo design system', () => {
      const code = generateAngularThemeSass({
        designSystem: 'indigo',
        variant: 'light',
      });

      expect(code).toContain('$indigo-typeface');
      expect(code).toContain('$indigo-type-scale');
    });

    it('uses custom font family when provided', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        fontFamily: 'Inter',
      });

      expect(code).toContain("'Inter'");
      // Should not use the preset typeface variable
      expect(code).not.toContain('$material-typeface');
    });

    it('excludes typography when includeTypography is false', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        includeTypography: false,
      });

      expect(code).not.toContain('@include typography(');
    });
  });

  describe('custom palette', () => {
    it('generates custom palette when colors are provided', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        primaryColor: '#2ab759',
        secondaryColor: '#f7bd32',
        surfaceColor: '#ffffff',
      });

      expect(code).toContain('$primary-color: #2ab759');
      expect(code).toContain('$secondary-color: #f7bd32');
      expect(code).toContain('$surface-color: #ffffff');
      expect(code).toContain('palette(');
    });

    it('uses custom palette name when provided', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        primaryColor: '#2ab759',
        customPaletteName: '$corporate-palette',
      });

      expect(code).toContain('$corporate-palette');
    });

    it('uses preset palette when no custom colors', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
      });

      expect(code).toContain('$light-material-palette');
      // Should not have custom color variables
      expect(code).not.toContain('$primary-color:');
    });

    it('includes gray color when provided', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        primaryColor: '#2ab759',
        grayColor: '#9e9e9e',
      });

      expect(code).toContain('$gray-color: #9e9e9e');
    });
  });

  describe('design systems and variants', () => {
    it('uses correct schema for light material', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
      });

      expect(code).toContain('$light-material-schema');
    });

    it('uses correct schema for dark material', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'dark',
      });

      expect(code).toContain('$dark-material-schema');
    });

    it('uses correct schema for dark indigo', () => {
      const code = generateAngularThemeSass({
        designSystem: 'indigo',
        variant: 'dark',
      });

      expect(code).toContain('$dark-indigo-schema');
    });

    it('uses correct schema for light fluent', () => {
      const code = generateAngularThemeSass({
        designSystem: 'fluent',
        variant: 'light',
      });

      expect(code).toContain('$light-fluent-schema');
    });

    it('uses correct schema for light bootstrap', () => {
      const code = generateAngularThemeSass({
        designSystem: 'bootstrap',
        variant: 'light',
      });

      expect(code).toContain('$light-bootstrap-schema');
    });

    it('uses correct palette for dark indigo preset', () => {
      const code = generateAngularThemeSass({
        designSystem: 'indigo',
        variant: 'dark',
      });

      expect(code).toContain('$dark-indigo-palette');
    });
  });

  describe('core mixin options', () => {
    it('defaults to core() with no arguments', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
      });

      expect(code).toContain('@include core();');
    });

    it('adds $print-layout: false when specified', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        coreOptions: {
          printLayout: false,
        },
      });

      expect(code).toContain('@include core($print-layout: false)');
    });

    it('adds $enhanced-accessibility: true when specified', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        coreOptions: {
          enhancedAccessibility: true,
        },
      });

      expect(code).toContain('@include core($enhanced-accessibility: true)');
    });

    it('combines multiple core options', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        coreOptions: {
          printLayout: false,
          enhancedAccessibility: true,
        },
      });

      expect(code).toContain('@include core($print-layout: false, $enhanced-accessibility: true)');
    });
  });

  describe('theme mixin options', () => {
    it('adds $roundness when specified', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        themeOptions: {
          roundness: 0.5,
        },
      });

      expect(code).toContain('$roundness: 0.5');
    });

    it('adds $elevation: false when specified', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        themeOptions: {
          elevation: false,
        },
      });

      expect(code).toContain('$elevation: false');
    });

    it('adds custom $elevations when specified', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        themeOptions: {
          elevations: '$custom-elevations',
        },
      });

      expect(code).toContain('$elevations: $custom-elevations');
    });

    it('adds $exclude list when specified', () => {
      const code = generateAngularThemeSass({
        designSystem: 'material',
        variant: 'light',
        themeOptions: {
          exclude: ['igx-avatar', 'igx-badge'],
        },
      });

      expect(code).toContain('$exclude: (igx-avatar, igx-badge)');
    });
  });
});
