/**
 * Tests for Web Components helper functions.
 *
 * These tests verify the smaller, focused helper functions extracted
 * during the refactoring of generateWebComponentsThemeSass.
 */

import { describe, expect, it } from "vitest";
import {
	generateWCHeader,
	generateWCImports,
	generateWCProgressProperties,
	generateWCRootVariables,
	generateWCRtlSupport,
	generateWCScrollbarCustomization,
	generateWCThemingMixins,
	generateWebComponentsThemeSass,
	getWCElevationPreset,
} from "../../knowledge/platforms/webcomponents.js";

describe("generateWCHeader", () => {
	it("returns correct header lines", () => {
		const header = generateWCHeader();
		expect(header).toContain("// Generated by Ignite UI Theming MCP Server");
		expect(header).toContain("// Platform: Ignite UI for Web Components");
		expect(header).toHaveLength(3); // Two comment lines + empty line
	});
});

describe("getWCElevationPreset", () => {
	it("returns indigo elevations for indigo design system", () => {
		expect(getWCElevationPreset("indigo")).toBe("$indigo-elevations");
	});

	it("returns material elevations for material design system", () => {
		expect(getWCElevationPreset("material")).toBe("$material-elevations");
	});

	it("returns material elevations for fluent design system", () => {
		expect(getWCElevationPreset("fluent")).toBe("$material-elevations");
	});

	it("returns material elevations for bootstrap design system", () => {
		expect(getWCElevationPreset("bootstrap")).toBe("$material-elevations");
	});
});

describe("generateWCImports", () => {
	it("generates imports for custom colors", () => {
		const imports = generateWCImports({
			designSystem: "material",
			variant: "light",
			hasCustomColors: true,
			includeTypography: true,
			includeElevations: true,
		});

		expect(imports.join("\n")).toContain("@use 'igniteui-theming' as *;");
		expect(imports.join("\n")).toContain(
			"@use 'igniteui-theming/sass/typography/presets/material' as *;",
		);
		expect(imports.join("\n")).toContain(
			"@use 'igniteui-theming/sass/elevations/presets' as *;",
		);
	});

	it("generates imports for preset palette", () => {
		const imports = generateWCImports({
			designSystem: "indigo",
			variant: "dark",
			hasCustomColors: false,
			includeTypography: true,
			includeElevations: true,
		});

		expect(imports.join("\n")).toContain(
			"@use 'igniteui-theming/sass/color/presets/dark/indigo' as *;",
		);
		expect(imports.join("\n")).toContain("@use 'igniteui-theming' as *;");
		expect(imports.join("\n")).toContain(
			"@use 'igniteui-theming/sass/typography/presets/indigo' as *;",
		);
	});

	it("skips typography import when not included", () => {
		const imports = generateWCImports({
			designSystem: "material",
			variant: "light",
			hasCustomColors: false,
			includeTypography: false,
			includeElevations: true,
		});

		expect(imports.join("\n")).not.toContain("typography/presets");
	});

	it("skips elevations import when not included", () => {
		const imports = generateWCImports({
			designSystem: "material",
			variant: "light",
			hasCustomColors: false,
			includeTypography: true,
			includeElevations: false,
		});

		expect(imports.join("\n")).not.toContain("elevations/presets");
	});
});

describe("generateWCProgressProperties", () => {
	it("generates progress property declarations", () => {
		const props = generateWCProgressProperties();
		const output = props.join("\n");

		expect(output).toContain("@property --_progress-integer");
		expect(output).toContain("@property --_progress-fraction");
		expect(output).toContain("syntax: '<integer>'");
		expect(output).toContain("initial-value: 0");
		expect(output).toContain("inherits: true");
	});

	it("applies indent when specified", () => {
		const props = generateWCProgressProperties("  ");
		expect(props[0].startsWith("  @property")).toBe(true);
		expect(props[1].startsWith("    syntax")).toBe(true);
	});
});

describe("generateWCRootVariables", () => {
	it("generates root variables with literal values for preset palette", () => {
		const vars = generateWCRootVariables({
			designSystem: "material",
			variant: "light",
			usePaletteMap: false,
		});
		const output = vars.join("\n");

		expect(output).toContain(":root {");
		expect(output).toContain("--ig-theme: material");
		expect(output).toContain("--ig-theme-variant: light");
		expect(output).toContain("--ig-size-small: 1");
		expect(output).toContain("--ig-size-medium: 2");
		expect(output).toContain("--ig-size-large: 3");
		expect(output).toContain("--ig-scrollbar-size: #{rem(16px)}");
	});

	it("generates root variables with map.get for custom palette", () => {
		const vars = generateWCRootVariables({
			designSystem: "indigo",
			variant: "dark",
			usePaletteMap: true,
		});
		const output = vars.join("\n");

		expect(output).toContain(
			"--ig-theme: #{map.get($palette, '_meta', 'variant')}",
		);
		expect(output).toContain("--ig-theme-variant: #{$variant}");
	});

	it("applies indent when specified", () => {
		const vars = generateWCRootVariables({
			designSystem: "material",
			variant: "light",
			indent: "  ",
		});
		expect(vars[0]).toBe("  :root {");
	});
});

describe("generateWCRtlSupport", () => {
	it("generates RTL direction support", () => {
		const rtl = generateWCRtlSupport();
		const output = rtl.join("\n");

		expect(output).toContain("body[dir='rtl']");
		expect(output).toContain("--ig-dir: -1");
	});

	it("applies indent when specified", () => {
		const rtl = generateWCRtlSupport("  ");
		expect(rtl[0]).toBe("  body[dir='rtl'] {");
	});
});

describe("generateWCScrollbarCustomization", () => {
	it("generates scrollbar customization using color function", () => {
		const scrollbar = generateWCScrollbarCustomization();
		const output = scrollbar.join("\n");

		expect(output).toContain("// Scrollbar customization");
		expect(output).toContain(":root {");
		expect(output).toContain("--ig-scrollbar-thumb-background");
		expect(output).toContain("--ig-scrollbar-track-background");
		expect(output).toContain("color($color: gray, $variant: 400)");
		expect(output).toContain("color($color: gray, $variant: 100)");
	});
});

describe("generateWCThemingMixins", () => {
	it("generates all theming mixins", () => {
		const mixins = generateWCThemingMixins({
			paletteVar: "$my-palette",
			typefaceValue: "$typeface",
			elevationsVar: "$material-elevations",
			includeTypography: true,
			includeElevations: true,
			includeSpacing: true,
		});
		const output = mixins.join("\n");

		expect(output).toContain("@include palette($my-palette)");
		expect(output).toContain("@include elevations($material-elevations)");
		expect(output).toContain("@include typography(");
		expect(output).toContain("$font-family: '$typeface'"); // quoteFontFamily adds quotes
		expect(output).toContain("@include spacing()");
	});

	it("skips mixins when not included", () => {
		const mixins = generateWCThemingMixins({
			paletteVar: "$palette",
			typefaceValue: "$typeface",
			elevationsVar: "$material-elevations",
			includeTypography: false,
			includeElevations: false,
			includeSpacing: false,
		});
		const output = mixins.join("\n");

		expect(output).toContain("@include palette($palette)");
		expect(output).not.toContain("@include elevations");
		expect(output).not.toContain("@include typography");
		expect(output).not.toContain("@include spacing");
	});

	it("adds comments when requested", () => {
		const mixins = generateWCThemingMixins({
			paletteVar: "$palette",
			typefaceValue: "$typeface",
			elevationsVar: "$material-elevations",
			includeTypography: true,
			includeElevations: true,
			includeSpacing: true,
			addComments: true,
		});
		const output = mixins.join("\n");

		expect(output).toContain("// Apply palette CSS variables");
		expect(output).toContain("// Apply elevation CSS variables");
		expect(output).toContain("// Apply typography CSS variables");
		expect(output).toContain("// Apply spacing CSS variables");
	});

	it("applies indent when specified", () => {
		const mixins = generateWCThemingMixins({
			paletteVar: "$palette",
			typefaceValue: "$typeface",
			elevationsVar: "$material-elevations",
			includeTypography: true,
			includeElevations: true,
			includeSpacing: true,
			indent: "  ",
		});

		expect(mixins[0]).toBe("  @include palette($palette);");
	});
});

describe("generateWebComponentsThemeSass (integration)", () => {
	it("generates complete theme for preset palette", () => {
		const code = generateWebComponentsThemeSass({
			designSystem: "material",
			variant: "light",
		});

		// Header
		expect(code).toContain("// Generated by Ignite UI Theming MCP Server");
		expect(code).toContain("// Platform: Ignite UI for Web Components");

		// Imports
		expect(code).toContain(
			"@use 'igniteui-theming/sass/color/presets/light/material' as *;",
		);
		expect(code).toContain("@use 'igniteui-theming' as *;");

		// Root variables
		expect(code).toContain("--ig-theme: material");
		expect(code).toContain("--ig-theme-variant: light");

		// Mixins
		expect(code).toContain("@include palette($palette)");
		expect(code).toContain("@include elevations($material-elevations)");
		expect(code).toContain("@include typography(");
		expect(code).toContain("@include spacing()");
	});

	it("generates complete theme for custom palette", () => {
		const code = generateWebComponentsThemeSass({
			designSystem: "indigo",
			variant: "dark",
			primaryColor: "#2ab759",
			secondaryColor: "#f7bd32",
			surfaceColor: "#1a1a1a",
		});

		// Header
		expect(code).toContain("// Platform: Ignite UI for Web Components");

		// Custom palette
		expect(code).toContain("$primary-color: #2ab759");
		expect(code).toContain("$secondary-color: #f7bd32");
		expect(code).toContain("$surface-color: #1a1a1a");
		expect(code).toContain("$my-palette: palette(");

		// Theme mixin wrapper
		expect(code).toContain("@mixin theme($palette, $variant)");
		expect(code).toContain("@include theme($my-palette, 'dark')");
	});

	it("respects includeTypography option", () => {
		const codeWithTypography = generateWebComponentsThemeSass({
			designSystem: "material",
			variant: "light",
			includeTypography: true,
		});

		const codeWithoutTypography = generateWebComponentsThemeSass({
			designSystem: "material",
			variant: "light",
			includeTypography: false,
		});

		expect(codeWithTypography).toContain("@include typography(");
		expect(codeWithoutTypography).not.toContain("@include typography(");
	});

	it("respects includeElevations option", () => {
		const codeWithElevations = generateWebComponentsThemeSass({
			designSystem: "material",
			variant: "light",
			includeElevations: true,
		});

		const codeWithoutElevations = generateWebComponentsThemeSass({
			designSystem: "material",
			variant: "light",
			includeElevations: false,
		});

		expect(codeWithElevations).toContain("@include elevations(");
		expect(codeWithoutElevations).not.toContain("@include elevations(");
	});

	it("respects includeSpacing option", () => {
		const codeWithSpacing = generateWebComponentsThemeSass({
			designSystem: "material",
			variant: "light",
			includeSpacing: true,
		});

		const codeWithoutSpacing = generateWebComponentsThemeSass({
			designSystem: "material",
			variant: "light",
			includeSpacing: false,
		});

		expect(codeWithSpacing).toContain("@include spacing()");
		expect(codeWithoutSpacing).not.toContain("@include spacing()");
	});
});
